-- where 절 equi join  문제
SELECT SUM(CITY.POPULATION) 
FROM CITY, COUNTRY
WHERE CITY.COUNTRYCODE = COUNTRY.CODE AND COUNTRY.CONTINENT = 'Asia';

SELECT A.Name
FROM CITY A, COUNTRY B
WHERE B.Code = A.CountryCode
AND B.Continent = 'Africa';

-- where 절 equi join 문제
SELECT COUNTRY.CONTINENT, FLOOR(AVG(CITY.POPULATION))
FROM CITY , COUNTRY 
WHERE COUNTRY.CODE = CITY.COUNTRYCODE
GROUP BY COUNTRY.CONTINENT;