WITH BASE AS (
    SELECT 'aA11'   AS ID FROM DUAL UNION ALL   
    SELECT '1qw211e' AS ID FROM DUAL UNION ALL   
    SELECT '1qwe#'  AS ID FROM DUAL UNION ALL   
    SELECT 'e*'     AS ID FROM DUAL UNION ALL   
    SELECT '@!'     AS ID FROM DUAL UNION ALL   
    SELECT '123'    AS ID FROM DUAL)
SELECT ID FROM BASE
 WHERE REGEXP_LIKE(ID, '[^[:digit:]]');

-- 하나라도 숫자가 아닌것이 있으면  선택
